environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"

install:
  - ps: Start-FileDownload 'https://raw.github.com/pypa/pip/master/contrib/get-pip.py'
  - '%PYTHON%\\python.exe get-pip.py'
  - '%PYTHON%\\Scripts\\pip.exe install . --no-clean'

build_script: '%PYTHON%\\Scripts\\pip.exe install pytest coveralls docopt'

test_script:
  - '%PYTHON%\\python.exe setup.py test'
  - '%PYTHON%\\python.exe example.py print'

after_test: '%PYTHON%\\Scripts\\coveralls.exe'
